# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53003e9c3ecb10963f5245d7e41fdca49dc6681646e4a5efbf54d061127d2667a2456af821034d67d0afdabadb23b3a3b22228a9cbf4ba42595413ff909ea292

test:
  secret_key_base: 630ac28c473eb2abb9e3b3db1c9b0dde633383501b0d76744fa1fee0719dc859b0675aa56284cf1023145bbcbc161c6a4d1800c131479b52d51de7c8c6e0e0ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
